import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import SectionContainer from "@/components/layouts/SectionContainer";
import MainNavbar from "@/components/layouts/Navbar";

const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="bg-[#fbf5e9] min-h-screen scroll-smooth">
          <SectionContainer>
            <MainNavbar />
            {children}
          </SectionContainer>
        </main>
      </body>
    </html>
  );
}
